ignore:
  - ".data"

# fixes:
#   - "workspaces/gem-client/::gem/clients/gem/"
#   - "app/::gem/apps/gem/"

coverage:
  status:
    project:
      default:
        target: 90%
        threshold: null
      app:
        flags: app
        target: 90%
      client:
        target: 50%
        flags: client
flags:
  app:  
    paths:
      - gem/apps/gem
  client:
    paths:
      - gem/client/gem
