version: "3"
services:
  gem-client:
    restart: on-failure:5
    build: ./clients/gem
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - gem-app
  gem-app:
    build: ./apps/gem
    ports:
      - 9000:9000
    depends_on:
      - db
  db:
    build: ./db
    restart: always
    env_file:
      - environment.env
    ports:
      - 5432:5432
    volumes:
      - "../.data/db:/var/lib/postgresql/data"
