version: "3"
services:
  gem-client:
    restart: on-failure:5
    build: ./clients/gem
    ports:
      - ${GEM_CLIENT_PORT}:${GEM_CLIENT_PORT}
    depends_on:
      - gem-app
    env_file:
      - .env
  gem-app:
    build: ./apps/gem
    ports:
      - ${GEM_APP_PORT}:${GEM_APP_PORT}
    depends_on:
      - db
    env_file:
      - .env
  db:
    build: ./db
    restart: always
    env_file:
      - .env
    ports:
      - ${GEM_DB_PORT}:${GEM_DB_PORT}
    volumes:
      - "../.data/db:/var/lib/postgresql/data"
