version: "3"
services:
  gem-client:
    restart: on-failure:5
    build: ./clients/gem
    expose:
      - 8080
    ports:
      - 8080:8080
  gem-app:
    build: ./apps/gem
    ports:
      - "9000:9000"
    #volumes:
    #  - ./frontend/api/app:/app
    #depends_on:
    #  - mongo
    depends_on:
      - gem-db
  gem-db:
    build: ./db
    restart: always
    env_file:
     - environment.env
    ports:
      - "5432:5432"
    volumes:
      - "./db/postgres_data:/var/lib/postgresql/data"
