version: "3"
services:
  gem-client:
    restart: on-failure:5
    build: ./clients/gem
    ports:
      - ${GEM_CLIENT_PORT-8080}:${GEM_CLIENT_PORT-8080}
    depends_on:
      - gem-app
    env_file:
      - .env
  gem-app:
    restart: on-failure:5
    build: ./apps/gem
    ports:
      - ${GEM_APP_PORT-9000}:${GEM_APP_PORT-9000}
    depends_on:
      - db
    env_file:
      - .env
  db:
    build: ./db
    restart: always
    env_file:
      - .env
    ports:
      - ${GEM_DB_PORT-5432}:${GEM_DB_PORT-5432}
    volumes:
      - "../.data/db:/var/lib/postgresql/data"
